# Use an official Python runtime as a parent image
FROM python:3.12.0

WORKDIR /app


COPY sarima.py /app/sarima.py

COPY data/metrics.csv /app/data/metrics.csv

RUN pip install pandas numpy matplotlib statsmodels scikit-learn

CMD ["python", "sarima.py", "load_data"]
