apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: sarima-pipeline-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.22, pipelines.kubeflow.org/pipeline_compilation_time: '2024-07-14T02:22:16.796796',
    pipelines.kubeflow.org/pipeline_spec: '{"description": "A pipeline to run SARIMA
      model functions.", "name": "SARIMA Pipeline"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.22}
spec:
  entrypoint: sarima-pipeline
  templates:
  - name: adf-test
    container:
      command: [python, sarima.py, test_stationarity]
      image: wasiue/test_stationarity:latest
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.22
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
  - name: difference-series
    container:
      command: [python, sarima.py, difference_series]
      image: wasiue/difference_series:latest
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.22
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
  - name: load-data
    container:
      command: [python, sarima.py, load_data]
      image: wasiue/load_data:latest
    outputs:
      artifacts:
      - {name: load-data-data, path: /app/data/metrics.csv}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.22
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
  - name: main-execution
    container:
      command: [python, sarima.py, main]
      image: wasiue/main:latest
    outputs:
      artifacts:
      - {name: main-execution-data, path: /app/data/metrics.csv}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.22
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
  - name: plot-acf-and-pacf
    container:
      command: [python, sarima.py, plot_acf_pacf]
      image: wasiue/plot_acf_pacf:latest
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.22
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
  - name: sarima-forecasting
    container:
      command: [python, sarima.py, sarima_model]
      image: wasiue/sarima_model:latest
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.22
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
  - name: sarima-pipeline
    dag:
      tasks:
      - name: adf-test
        template: adf-test
        dependencies: [seasonal-decomposition]
      - name: difference-series
        template: difference-series
        dependencies: [adf-test]
      - name: load-data
        template: load-data
        dependencies: [main-execution]
      - {name: main-execution, template: main-execution}
      - name: plot-acf-and-pacf
        template: plot-acf-and-pacf
        dependencies: [difference-series]
      - name: sarima-forecasting
        template: sarima-forecasting
        dependencies: [plot-acf-and-pacf]
      - name: seasonal-decomposition
        template: seasonal-decomposition
        dependencies: [load-data]
  - name: seasonal-decomposition
    container:
      command: [python, sarima.py, seasonal_decomposition]
      image: wasiue/seasonal_decomposition:latest
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.22
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
  arguments:
    parameters: []
  serviceAccountName: pipeline-runner
